# Generated by Django 5.0.2 on 2024-03-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='stafff_id',
            new_name='staff_id',
        ),
        migrations.CreateModel(
            name='DoubtSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doubt_message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
            ],
        ),
    ]
